namespace Latihan2.Case
{
    public class DataProduct
    {
        public class Product
        {
            public int No { get; set; }
            public string ProductName { get; set; } = "";
            public decimal Price { get; set; }
            public string Unit { get; set; } = "";
        }

        public List<Product> GetProducts()
        {
            return new List<Product>()
            {
                new Product { No = 1, ProductName = "Laptop", Price = 12000000, Unit = "Unit" },
                new Product { No = 2, ProductName = "Smartphone", Price = 3500000, Unit = "Unit" },
                new Product { No = 3, ProductName = "Keyboard", Price = 350000, Unit = "Unit" },
                new Product { No = 4, ProductName = "Mouse", Price = 150000, Unit = "Unit" },
                new Product { No = 5, ProductName = "Monitor", Price = 2000000, Unit = "Unit" },
                new Product { No = 6, ProductName = "Flashdisk", Price = 120000, Unit = "Unit" },
                new Product { No = 7, ProductName = "Hard Drive", Price = 1000000, Unit = "Unit" },
                new Product { No = 8, ProductName = "Power Bank", Price = 400000, Unit = "Unit" },
                new Product { No = 9, ProductName = "Earphone", Price = 250000, Unit = "Unit" },
                new Product { No = 10, ProductName = "Speaker", Price = 600000, Unit = "Unit" },
                new Product { No = 11, ProductName = "Printer", Price = 1500000, Unit = "Unit" },
                new Product { No = 12, ProductName = "Camera", Price = 5000000, Unit = "Unit" },
                new Product { No = 13, ProductName = "Tablet", Price = 4000000, Unit = "Unit" },
                new Product { No = 14, ProductName = "Headset", Price = 500000, Unit = "Unit" },
                new Product { No = 15, ProductName = "Smartwatch", Price = 1800000, Unit = "Unit" },
                new Product { No = 16, ProductName = "Drone", Price = 7000000, Unit = "Unit" },
                new Product { No = 17, ProductName = "VR Headset", Price = 3000000, Unit = "Unit" },
                new Product { No = 18, ProductName = "Router", Price = 600000, Unit = "Unit" },
                new Product { No = 19, ProductName = "External Monitor", Price = 2500000, Unit = "Unit" },
                new Product { No = 20, ProductName = "Microphone", Price = 750000, Unit = "Unit" },
                new Product { No = 21, ProductName = "Laptop Stand", Price = 200000, Unit = "Unit" },
                new Product { No = 22, ProductName = "Cooling Pad", Price = 150000, Unit = "Unit" },
                new Product { No = 23, ProductName = "Gaming Mouse", Price = 500000, Unit = "Unit" },
                new Product { No = 24, ProductName = "Wireless Charger", Price = 250000, Unit = "Unit" },
                new Product { No = 25, ProductName = "HDMI Cable", Price = 100000, Unit = "Unit" },
                new Product { No = 26, ProductName = "Laptop Sleeve", Price = 200000, Unit = "Unit" },
                new Product { No = 27, ProductName = "Webcam", Price = 350000, Unit = "Unit" },
                new Product { No = 28, ProductName = "Smartphone Case", Price = 150000, Unit = "Unit" },
                new Product { No = 29, ProductName = "USB Hub", Price = 120000, Unit = "Unit" },
                new Product { No = 30, ProductName = "Power Adapter", Price = 180000, Unit = "Unit" },
                new Product { No = 31, ProductName = "Digital Camera", Price = 4500000, Unit = "Unit" },
                new Product { No = 32, ProductName = "Wireless Earbud", Price = 600000, Unit = "Unit" },
                new Product { No = 33, ProductName = "Phone Stand", Price = 80000, Unit = "Unit" },
                new Product { No = 34, ProductName = "SSD", Price = 800000, Unit = "Unit" },
                new Product { No = 35, ProductName = "Memory Card", Price = 250000, Unit = "Unit" },
                new Product { No = 36, ProductName = "Phone Charger", Price = 100000, Unit = "Unit" },
                new Product { No = 37, ProductName = "Laptop Charger", Price = 250000, Unit = "Unit" },
                new Product { No = 38, ProductName = "Portable Speaker", Price = 500000, Unit = "Unit" },
                new Product { No = 39, ProductName = "Smartphone Holder", Price = 150000, Unit = "Unit" },
                new Product { No = 40, ProductName = "Game Console", Price = 4000000, Unit = "Unit" },
                new Product { No = 41, ProductName = "VR Glasses", Price = 2500000, Unit = "Unit" },
                new Product { No = 42, ProductName = "Security Camera", Price = 800000, Unit = "Unit" },
                new Product { No = 43, ProductName = "Electric Kettle", Price = 300000, Unit = "Unit" },
                new Product { No = 44, ProductName = "Toaster", Price = 250000, Unit = "Unit" },
                new Product { No = 45, ProductName = "Coffee Machine", Price = 1200000, Unit = "Unit" },
                new Product { No = 46, ProductName = "Air Conditioner", Price = 3500000, Unit = "Unit" },
                new Product { No = 47, ProductName = "Blender", Price = 400000, Unit = "Unit" },
                new Product { No = 48, ProductName = "Juicer", Price = 350000, Unit = "Unit" },
                new Product { No = 49, ProductName = "Vacuum Cleaner", Price = 1500000, Unit = "Unit" },
                new Product { No = 50, ProductName = "Electric Fan", Price = 250000, Unit = "Unit" },
                new Product { No = 51, ProductName = "Microwave Oven", Price = 1800000, Unit = "Unit" },
                new Product { No = 52, ProductName = "Refrigerator", Price = 4000000, Unit = "Unit" },
                new Product { No = 53, ProductName = "Washing Machine", Price = 3000000, Unit = "Unit" },
                new Product { No = 54, ProductName = "Iron", Price = 200000, Unit = "Unit" },
                new Product { No = 55, ProductName = "Hair Dryer", Price = 150000, Unit = "Unit" },
                new Product { No = 56, ProductName = "Rice Cooker", Price = 400000, Unit = "Unit" },
                new Product { No = 57, ProductName = "Food Processor", Price = 800000, Unit = "Unit" },
                new Product { No = 58, ProductName = "Air Purifier", Price = 2000000, Unit = "Unit" },
                new Product { No = 59, ProductName = "Electric Stove", Price = 350000, Unit = "Unit" },
                new Product { No = 60, ProductName = "Water Heater", Price = 1200000, Unit = "Unit" },
                new Product { No = 61, ProductName = "Water Dispenser", Price = 1500000, Unit = "Unit" },
                new Product { No = 62, ProductName = "Grill", Price = 600000, Unit = "Unit" },
                new Product { No = 63, ProductName = "Slow Cooker", Price = 500000, Unit = "Unit" },
                new Product { No = 64, ProductName = "Induction Cooker", Price = 900000, Unit = "Unit" },
                new Product { No = 65, ProductName = "Ice Cream Maker", Price = 600000, Unit = "Unit" },
                new Product { No = 66, ProductName = "Stand Mixer", Price = 800000, Unit = "Unit" },
                new Product { No = 67, ProductName = "Wall Clock", Price = 150000, Unit = "Unit" },
                new Product { No = 68, ProductName = "Desk Lamp", Price = 250000, Unit = "Unit" },
                new Product { No = 69, ProductName = "Bed Lamp", Price = 200000, Unit = "Unit" },
                new Product { No = 70, ProductName = "Ceiling Fan", Price = 500000, Unit = "Unit" },
                new Product { No = 71, ProductName = "Standing Fan", Price = 300000, Unit = "Unit" },
                new Product { No = 72, ProductName = "Electric Heater", Price = 700000, Unit = "Unit" },
                new Product { No = 73, ProductName = "Air Humidifier", Price = 400000, Unit = "Unit" },
                new Product { No = 74, ProductName = "Digital Thermometer", Price = 150000, Unit = "Unit" },
                new Product { No = 75, ProductName = "Scale", Price = 100000, Unit = "Unit" },
                new Product { No = 76, ProductName = "Smart Scale", Price = 350000, Unit = "Unit" },
                new Product { No = 77, ProductName = "Blood Pressure Monitor", Price = 400000, Unit = "Unit" },
                new Product { No = 78, ProductName = "Thermometer", Price = 75000, Unit = "Unit" },
                new Product { No = 79, ProductName = "First Aid Kit", Price = 250000, Unit = "Unit" },
                new Product { No = 80, ProductName = "Vacuum Pump", Price = 350000, Unit = "Unit" },
                new Product { No = 81, ProductName = "Blood Glucose Meter", Price = 300000, Unit = "Unit" },
                new Product { No = 82, ProductName = "Electric Toothbrush", Price = 200000, Unit = "Unit" },
                new Product { No = 83, ProductName = "Hair Clipper", Price = 150000, Unit = "Unit" },
                new Product { No = 84, ProductName = "Shaver", Price = 100000, Unit = "Unit" },
                new Product { No = 85, ProductName = "Foot Massager", Price = 800000, Unit = "Unit" },
                new Product { No = 86, ProductName = "Neck Massager", Price = 500000, Unit = "Unit" },
                new Product { No = 87, ProductName = "Hand Massager", Price = 300000, Unit = "Unit" },
                new Product { No = 88, ProductName = "Massage Chair", Price = 3000000, Unit = "Unit" },
                new Product { No = 89, ProductName = "Face Steamer", Price = 250000, Unit = "Unit" },
                new Product { No = 90, ProductName = "Nail Clipper", Price = 50000, Unit = "Unit" },
                new Product { No = 91, ProductName = "Electric Razor", Price = 400000, Unit = "Unit" },
                new Product { No = 92, ProductName = "Hair Straightener", Price = 250000, Unit = "Unit" },
                new Product { No = 93, ProductName = "Hair Curler", Price = 200000, Unit = "Unit" },
                new Product { No = 94, ProductName = "Ironing Board", Price = 300000, Unit = "Unit" },
                new Product { No = 95, ProductName = "Shoe Dryer", Price = 350000, Unit = "Unit" },
                new Product { No = 96, ProductName = "Shoe Polisher", Price = 200000, Unit = "Unit" },
                new Product { No = 97, ProductName = "Smart Thermostat", Price = 1000000, Unit = "Unit" },
                new Product { No = 98, ProductName = "Doorbell", Price = 250000, Unit = "Unit" },
                new Product { No = 99, ProductName = "Light Bulb", Price = 50000, Unit = "Unit" },
                new Product { No = 100, ProductName = "Flashlight", Price = 150000, Unit = "Unit" }
            };
        }
    }
}